name: Show system info

on:
    workflow_dispatch:

jobs:
    echo_nproc:
        name: Show system info
        runs-on: ubuntu-24.04
        steps:
          - run: echo $(df -h)
          - run: cat /proc/cpuinfo
          - run: cat /proc/meminfo