name: Show system info

on:
    workflow_dispatch:

jobs:
    echo_nproc:
        name: Show system info
        runs-on: ubuntu-22.04
        steps:
          - name: Maximize build space
            uses: easimon/maximize-build-space@master
            with:
                remove-dotnet: 'true'
                remove-haskell: 'true'
                remove-codeql: 'true'
                remove-docker-images: 'true'
          - run: sudo docker image prune --all --force
          - run: sudo docker builder prune -a
          - run: df -h
          - run: cat /proc/cpuinfo
          - run: cat /proc/meminfo